#users-sys-api-listener
listener:
  protocol: "HTTP"
  host: "localhost"
  port: "8082"
  base-path: "/api/v1/*"
  console-path: "console/*"
  paths:
    users-request: "users"
  idle-timeout: "300000"
  read-timeout: "300000"
  
#mySQL-users-database:
mySQL-database:
  conn-name: users-db
  host: "127.0.0.1"
  port: "3306"
  user: "giancarlo-mule-01"
  pass: "mule_2025!"

#Log flow expressions
mule:
    log:
      expression:
        start: "StartFlowName: #[flow.name] \n CorrelationId: #[correlationId] \n DateTime: #[now()]"
        end: "EndFlowName: #[flow.name] \n CorrelationId: #[correlationId] \n DateTime: #[now()]"
        error: "FlowName: #[flow.name] \n CorrelationId: #[correlationId] \n DateTime: #[now()] \n errorType: #[error.errorType default 'MULE:ANY']"